FROM node:20-alpine

# Install OpenJDK (required for Firebase emulators) and bash
RUN apk add --no-cache openjdk21-jre bash

# Install firebase-tools globally
RUN npm install -g firebase-tools

WORKDIR /app

# Copy configurations
COPY firebase.json ./
COPY firestore.rules ./

EXPOSE 4000 8080 8085

CMD ["firebase", "emulators:start", "--project=utopian-pen-495514-a8"]
