/**
 * Enum for all possible job statuses in the application.
 * Identical status values must be shared across the services, hooks, store, and pages.
 * @readonly
 * @enum {string}
 */
export const JOB_STATUS = {
  IDLE: 'IDLE',               // Initial state before any upload
  UPLOADING: 'UPLOADING',     // Client-side file uploading to server
  PENDING: 'PENDING',         // Upload completed, worker hasn't started yet
  PROCESSING: 'PROCESSING',   // Document is being processed by the worker
  EXTRACTING: 'EXTRACTING',   // Text is being extracted from the PDF
  CHUNKING: 'CHUNKING',       // Extracted text is being chunked into sections
  SUMMARIZING: 'SUMMARIZING', // Deep reasoning summary is being generated by AI
  COMPLETED: 'COMPLETED',     // Job finished successfully
  FAILED: 'FAILED',           // Job failed during worker execution
};
